- name: Create nginx directory
  file:
    path: /opt/nginx
    state: directory
    mode: 644

- name: Delete old nginx config file
  file:
    path: /opt/nginx/nginx.conf
    state: absent

- name: Upload new nginx configuration file
  template:
    src: ../template/nginx.tmpl
    dest: /opt/nginx/nginx.conf

- name: Setup docker and set config path
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
    volumes:
        - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf